### ISSUE TITLE
Additional model weights pre-trained on Places dataset

### ISSUE THREAD

**Issue by SupratimH** [GKalliatakis/Keras-Application-Zoo#1]
Hi,

Thanks for sharing these pre-trained weights.
Is there any plan to release weights for any ResNet based model pre-trained on Places dataset?

**Comment by GKalliatakis** [comment]
Hi, 

If you are interested in contributing towards porting the ResNet-Places weights please let me know and I can give you some directions.

**Comment by SupratimH** [comment]
Hi Grigorios,

Sure, I would like to contribute. Shall I drop you an email on the email id mentioned in your profile for further discussion?

Thanks and Regards,
Supratim

**Comment by GKalliatakis** [comment]
Yes send me an email and we can take it from there cheers
